packages:
  - demos/*
  - packages/*
  - tools/*
  - docs/

ignoredBuiltDependencies:
  - '@journeyapps/wa-sqlite'
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - core-js-pure
  - detox
  - dtrace-provider
  - electron
  - electron-winstaller
  - esbuild
  - lmdb
  - lzma-native
  - msgpackr-extract
  - react-native-elements
  - supabase
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - better-sqlite3-multiple-ciphers
