packages:
  - packages/*
  - tools/*
  - docs/

catalog:
  '@journeyapps/wa-sqlite': ^1.5.0
  '@op-engineering/op-sqlite': ^15.2.2
  '@pnpm/workspace.find-packages': ^1000.0.55
  '@pnpm/workspace.read-manifest': ^1000.2.9
  '@rollup/plugin-alias': ^5.1.0
  '@rollup/plugin-commonjs': ^29.0.0
  '@rollup/plugin-inject': ^5.0.5
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-node-resolve': ^16.0.3
  '@rollup/plugin-replace': ^5.0.7
  '@rollup/plugin-terser': ^0.4.4
  '@rollup/plugin-typescript': ^12.1.4
  '@types/node': ^24.0.0
  '@types/uuid': ^9.0.6
  async-mutex: ^0.5.0
  bson: ^6.10.4
  comlink: ^4.4.2
  drizzle-orm: ^0.44.7
  eslint: ^8.57.1
  eslint-plugin-prettier: ^5.5.4
  glob: ^11.0.0
  js-logger: ^1.6.1
  jsdom: ^24.0.0
  kysely: ^0.28.0
  p-defer: ^4.0.1
  prettier: ^3.7.4
  react-native: ^0.83.0
  rollup: ^4.52.5
  rollup-plugin-dts: ^6.2.1
  typescript: ^5.5.3
  uuid: ^11.1.0
  vite: ^7.3.1
  vitest: ^3.2.4

onlyBuiltDependencies:
  - '@journeyapps/wa-sqlite'
  - '@swc/core'
  - better-sqlite3
  - better-sqlite3-multiple-ciphers
  - core-js
  - core-js-pure
  - detox
  - dtrace-provider
  - esbuild
  - swiftlint
