packages:
  - .

overrides:
  # @electron-forge depends on an older version of this using git dependency, which pnpm blocks.
  # The only breaking change is that this requires node 22 or later.
  "@electron/rebuild": ^4.0.4

allowBuilds:
  better-sqlite3: true
  electron: true
