packages:
  - .

overrides:
  # @electron-forge depends on an older version of this using git dependency, which pnpm blocks.
  # The only breaking change is that this requires node 22 or later.
  "@electron/rebuild": ^4.0.4

allowBuilds:
  electron: true
  electron-winstaller: false
  esbuild: false
  lzma-native: false


nodeLinker: hoisted
minimumReleaseAgeExclude:
  - 'electron@44.4.3'
trustPolicyExclude:
  - 'rollup@2.80.0' # Backport release published from trusted tag
  - 'chokidar@4.0.3'
  - 'semver@6.3.1||5.7.2'
  - 'undici-types@6.21.0'
