/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    LoginDetailsWidget: typeof import('./src/components/widgets/LoginDetailsWidget.vue')['default']
    NavigationPanel: typeof import('./src/components/navigation/NavigationPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoListDisplay: typeof import('./src/components/TodoListDisplay.vue')['default']
    TodoListDisplayQuery: typeof import('./src/components/TodoListDisplayQuery.vue')['default']
    TodoListDisplayWatchedQuery: typeof import('./src/components/TodoListDisplayWatchedQuery.vue')['default']
  }
}
