import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';

import * as jose from 'https://deno.land/x/jose@v4.14.4/index.ts';
import * as base64 from 'https://deno.land/std@0.196.0/encoding/base64.ts';

const powerSyncPublicKey = JSON.parse(
  new TextDecoder().decode(base64.decode(Deno.env.get('POWERSYNC_PUBLIC_KEY')!))
) as jose.JWK;

// This function serves the public key.
// PowerSync uses this to verify JWTs generated by the auth function.

serve((_req) => {
  return new Response(
    JSON.stringify({
      keys: [
        powerSyncPublicKey
        // Additional keys could be added here if desired
      ]
    }),
    { headers: { 'Content-Type': 'application/json' } }
  );
});
