/**
 * Set of generic interfaces to allow PowerSync compatibility with
 * different SQLite DB implementations.
 */

import { BaseListener, BaseObserver } from '../utils/BaseObserver.js';

/**
 * A SQLite value, either text, a number, a blob value or null.
 *
 * @public
 */
export type SqliteValue = string | number | bigint | number[] | Uint8Array | null;

/**
 * A record of SQLite values representing a row.
 */
type SqliteRecord = Record<string, SqliteValue>;

/**
 * A raw array-based result set representing rows returned by SQLite.
 *
 * @public
 */
export interface RawResultSet {
  /**
   * Names of columns in this result set. Every column has a name, so the length of this array is always equal to the
   * amount of columns in the result set.
   *
   * Note that column names are not necessarily unique, e.g. a `SELECT foo.user, bar.user FROM ...` will have
   * `['user', 'user']` in this array.
   */
  columnNames: string[];

  /**
   * Rows in the result set.
   *
   * Each row has a length equal to {@link RawResultSet.columnNames}.
   */
  rawRows: SqliteValue[][];
}

/**
 * A typed wrapper around a {@link RawResultSet} generated by mapping row arrays to JavaScript objects.
 *
 * @public
 */
export class ResultSet implements RawResultSet {
  columnNames: string[];
  rawRows: SqliteValue[][];

  /**
   * The amount of rows in the result set.
   */
  get length(): number {
    return this.rawRows.length;
  }

  /**
   * @deprecated Use {@link ResultSet.mapped} instead.
   */
  get _array(): any[] {
    return this.mapped();
  }

  /**
   * Maps each row in {@link RawResultSet.rawRows} into a JavaScript object.
   */
  mapped<T>(): T[] {
    return this.rawRows.map((row) => rowToRecord(this.columnNames, row));
  }

  item<T>(idx: number): T {
    return rowToRecord(this.columnNames, this.rawRows[idx]);
  }

  constructor(resultSet: RawResultSet) {
    this.columnNames = resultSet.columnNames;
    this.rawRows = resultSet.rawRows;
  }
}

function rowToRecord<T>(columnNames: string[], row: SqliteValue[]) {
  const record: SqliteRecord = {};
  columnNames.forEach((name, idx) => (record[name] = row[idx]));
  return record as T;
}

/**
 * Object returned by SQL Query executions.
 *
 * @public
 */
export type QueryResult<Rows extends RawResultSet = ResultSet> = {
  /** Represents the auto-generated row id if applicable. */
  insertId?: number;
  /**
   * Number of affected rows reported by SQLite for a write query.
   *
   * When using the default client-side [JSON-based view system](https://docs.powersync.com/architecture/client-architecture#client-side-schema-and-sqlite-database-structure),
   * `rowsAffected` may be `0` for successful `UPDATE` and `DELETE` statements.
   * Use a `RETURNING` clause and inspect `rows` when you need to confirm which rows changed.
   */
  rowsAffected?: number;
  /**
   * If the query returned rows, the result set containing returned values.
   */
  rows?: Rows;
};

/**
 * @public
 */
export interface DBGetUtils {
  /**
   *  Execute a read-only query and return results.
   *
   * @param sql - The SQL query to execute
   * @param parameters - Optional array of parameters to bind to the query
   * @returns An array of results
   */
  getAll<T>(sql: string, parameters?: any[]): Promise<T[]>;
  /**
   * Execute a read-only query and return the first result, or null if the ResultSet is empty.
   *
   * @param sql - The SQL query to execute
   * @param parameters - Optional array of parameters to bind to the query
   * @returns The first result if found, or null if no results are returned
   */
  getOptional<T>(sql: string, parameters?: any[]): Promise<T | null>;
  /**
   * Execute a read-only query and return the first result, error if the ResultSet is empty.
   *
   * @param sql - The SQL query to execute
   * @param parameters - Optional array of parameters to bind to the query
   * @returns The first result matching the query
   * @throws Error if no rows are returned
   */
  get<T>(sql: string, parameters?: any[]): Promise<T>;
}

/**
 * @public
 */
export interface SqlExecutor {
  /**
   * Execute a SQL write (INSERT/UPDATE/DELETE) query
   * and optionally return results.
   *
   * When using the default client-side [JSON-based view system](https://docs.powersync.com/architecture/client-architecture#client-side-schema-and-sqlite-database-structure),
   * the returned result's `rowsAffected` may be `0` for successful `UPDATE` and `DELETE` statements.
   * Use a `RETURNING` clause and inspect `result.rows` when you need to confirm which rows changed.
   *
   * @param sql - The SQL query to execute
   * @param parameters - Optional array of parameters to bind to the query
   * @returns The query result as an object with structured key-value pairs
   */
  execute: (query: string, params?: any[] | undefined) => Promise<QueryResult>;

  /**
   * Execute a SQL write (INSERT/UPDATE/DELETE) query directly on the database without any PowerSync processing.
   * This bypasses certain PowerSync abstractions and is useful for accessing the raw database results.
   *
   * @param sql - The SQL query to execute
   * @param parameters - Optional array of parameters to bind to the query
   * @returns The {@link QueryResult} with a {@link RawResultSet} representing each row as an array.
   */
  executeRaw: (query: string, params?: any[] | undefined) => Promise<QueryResult<RawResultSet>>;

  /**
   * Execute a write query (INSERT/UPDATE/DELETE) multiple times with each parameter set
   * and optionally return results.
   * This is faster than executing separately with each parameter set.
   *
   * @param sql - The SQL query to execute
   * @param parameters - Optional 2D array of parameter sets, where each inner array is a set of parameters for one execution
   * @returns The query result
   */
  executeBatch: (query: string, params?: any[][]) => Promise<QueryResult>;
}

/**
 * @public
 */
export abstract class LockContext implements SqlExecutor, DBGetUtils {
  /**
   * How the connection has been opened.
   *
   * `writer` indicates that the lock context is capable of writing to the database.
   * `queryOnly` indicates that the lock context has been opened in a readwrite mode, but a `PRAGMA query_only = TRUE`
   * disabled writes.
   * `readOnly` indicates that the lock context has been opened by passing `SQLITE_OPEN_READONLY` to `sqlite3_open_v2`.
   */
  abstract get connectionType(): 'writer' | 'queryOnly' | 'readOnly' | undefined;

  abstract executeRaw(query: string, params?: any[] | undefined): Promise<QueryResult<RawResultSet>>;

  async getAll<T>(sql: string, parameters?: any[]): Promise<T[]> {
    const { rows } = await this.execute(sql, parameters);
    return rows?.mapped() ?? [];
  }

  async getOptional<T>(sql: string, parameters?: any[]): Promise<T | null> {
    const { rows } = await this.execute(sql, parameters);
    if (rows && rows.length > 0) {
      return rows.item(0);
    }

    return null;
  }

  async get<T>(sql: string, parameters?: any[]): Promise<T> {
    const row = await this.getOptional<T>(sql, parameters);
    if (row == null) {
      throw new Error('Result set is empty');
    }

    return row;
  }

  async execute(query: string, params?: any[] | undefined): Promise<QueryResult> {
    const { insertId, rowsAffected, rows } = await this.executeRaw(query, params);
    return { insertId, rowsAffected, rows: rows && new ResultSet(rows) };
  }

  async executeBatch(query: string, params: any[][] = []): Promise<QueryResult> {
    // Emulate executeBatch by running statements individually.
    let lastInsertId: number | undefined;
    let rowsAffected = 0;
    for (const set of params) {
      const result = await this.execute(query, set);
      lastInsertId = result.insertId;
      rowsAffected += result.rowsAffected ?? 0;
    }

    return {
      rowsAffected,
      insertId: lastInsertId
    };
  }
}

/**
 * @public
 */
export interface Transaction extends LockContext {
  /** Commit multiple changes to the local DB using the Transaction context. */
  commit: () => Promise<QueryResult>;
  /** Roll back multiple attempted changes using the Transaction context. */
  rollback: () => Promise<QueryResult>;
}

/**
 * @public
 */
export interface BatchedUpdateNotification {
  tables: string[];
}

/**
 * @public
 */
export interface DBAdapterListener extends BaseListener {
  /**
   * Listener for table updates.
   * Allows for single table updates in order to maintain API compatibility
   * without the need for a major version bump
   * The DB adapter can also batch update notifications if supported.
   */
  tablesUpdated: (updateNotification: BatchedUpdateNotification) => void;
}

/**
 * @public
 */
export interface DBLockOptions {
  timeoutMs?: number;
}

/**
 * @public
 */
export abstract class DBAdapter extends BaseObserver<DBAdapterListener> implements SqlExecutor, DBGetUtils {
  abstract get name(): string;

  abstract close(): void | Promise<void>;

  abstract readLock<T>(fn: (tx: LockContext) => Promise<T>, options?: DBLockOptions): Promise<T>;
  abstract writeLock<T>(fn: (tx: LockContext) => Promise<T>, options?: DBLockOptions): Promise<T>;

  /**
   * This method refreshes the schema information across all connections. This is for advanced use cases, and should generally not be needed.
   */
  abstract refreshSchema(): Promise<void>;

  readTransaction<T>(fn: (tx: Transaction) => Promise<T>, options?: DBLockOptions): Promise<T> {
    return this.readLock((ctx) => TransactionImplementation.runWith(ctx, fn), options);
  }

  writeTransaction<T>(fn: (tx: Transaction) => Promise<T>, options?: DBLockOptions): Promise<T> {
    return this.writeLock((ctx) => TransactionImplementation.runWith(ctx, fn), options);
  }

  getAll<T>(sql: string, parameters?: any[]): Promise<T[]> {
    return this.readLock((ctx) => ctx.getAll(sql, parameters));
  }

  getOptional<T>(sql: string, parameters?: any[]): Promise<T | null> {
    return this.readLock((ctx) => ctx.getOptional(sql, parameters));
  }

  get<T>(sql: string, parameters?: any[]): Promise<T> {
    return this.readLock((ctx) => ctx.get(sql, parameters));
  }

  execute(query: string, params?: any[]): Promise<QueryResult> {
    return this.writeLock((ctx) => ctx.execute(query, params));
  }

  executeRaw(query: string, params?: any[]): Promise<QueryResult<RawResultSet>> {
    return this.writeLock((ctx) => ctx.executeRaw(query, params));
  }

  executeBatch(query: string, params?: any[][]): Promise<QueryResult> {
    return this.writeTransaction((tx) => tx.executeBatch(query, params));
  }
}

class TransactionImplementation extends LockContext {
  private finalized = false;

  constructor(private inner: LockContext) {
    super();
  }

  get connectionType() {
    return this.inner.connectionType;
  }

  async commit(): Promise<QueryResult> {
    if (this.finalized) {
      return { rowsAffected: 0 };
    }
    this.finalized = true;
    return this.inner.execute('COMMIT');
  }

  async rollback(): Promise<QueryResult> {
    if (this.finalized) {
      return { rowsAffected: 0 };
    }
    this.finalized = true;
    return this.inner.execute('ROLLBACK');
  }

  execute(query: string, params?: any[] | undefined): Promise<QueryResult> {
    return this.inner.execute(query, params);
  }

  executeRaw(query: string, params?: any[] | undefined): Promise<QueryResult<RawResultSet>> {
    return this.inner.executeRaw(query, params);
  }

  executeBatch(query: string, params?: any[][]): Promise<QueryResult> {
    return this.inner.executeBatch(query, params);
  }

  static async runWith<T>(ctx: LockContext, fn: (tx: Transaction) => Promise<T>): Promise<T> {
    let tx = new TransactionImplementation(ctx);

    // For write transactions, use BEGIN IMMEDIATE to immediately obtain a write lock on the database (instead of doing
    // that on the first statement). If we have a genuine read-only connection, we also use BEGIN IMMEDIATE there: In
    // WAL mode, that ensures we pin the current state of the database (instead of the state at the first statement in
    // the transaction). But if we have a "fake" read-only connection implemented through `pragma query_only = true`, we
    // can't use this trick because it would attempt to lock the connection. So there, we use a regular `BEGIN`
    // statement.
    const useBeginImmediate = ctx.connectionType != 'queryOnly';

    try {
      await ctx.execute(useBeginImmediate ? 'BEGIN IMMEDIATE' : 'BEGIN');

      const result = await fn(tx);
      await tx.commit();
      return result;
    } catch (ex) {
      try {
        await tx.rollback();
      } catch (ex2) {
        // In rare cases, a rollback may fail.
        // Safe to ignore.
      }
      throw ex;
    }
  }
}
