/**
 * 64-bit unsigned integer stored as a string in base-10.
 *
 * Not sortable as a string.
 *
 * @public
 */
export type OpId = string;

/**
 * Type of local change.
 *
 * @public
 */
export enum UpdateType {
  /** Insert or replace existing row. All non-null columns are included in the data. Generated by INSERT statements. */
  PUT = 'PUT',
  /** Update existing row. Contains the id, and value of each changed column. Generated by UPDATE statements. */
  PATCH = 'PATCH',
  /** Delete existing row. Contains the id. Generated by DELETE statements. */
  DELETE = 'DELETE'
}

/**
 * A single client-side change.
 *
 * @public
 */
export interface CrudEntry {
  /**
   * Auto-incrementing client-side id.
   */
  clientId: number;
  /**
   * ID of the changed row.
   */
  id: string;
  /**
   * Type of change.
   */
  op: UpdateType;
  /**
   * Data associated with the change.
   */
  opData?: Record<string, any>;

  /**
   * For tables where the `trackPreviousValues` option has been enabled, this tracks previous values for
   * `UPDATE` and `DELETE` statements.
   */
  previousValues?: Record<string, any>;

  /**
   * Table that contained the change.
   */
  table: string;
  /**
   * Auto-incrementing transaction id. This is the same for all operations within the same transaction.
   */
  transactionId?: number;

  /**
   * Client-side metadata attached with this write.
   *
   * This field is only available when the `trackMetadata` option was set to `true` when creating a table
   * and the insert or update statement set the `_metadata` column.
   */
  metadata?: string;

  /**
   * Converts the change to JSON format.
   */
  toJSON(): unknown;

  equals(entry: CrudEntry): boolean;

  /**
   * Generates an array for use in deep comparison operations
   */
  toComparisonArray(): unknown[];
}
