# Adds YAML Schema support for VSCode users with the YAML extension installed. This enables features like validation and autocompletion based on the provided schema.
# yaml-language-server: $schema=https://unpkg.com/@powersync/service-sync-rules@latest/schema/sync_rules.json

# See https://docs.powersync.com/sync/advanced/compatibility
config:
  edition: 3

streams:
  user_data:
    with:
      # Extract the Convex user ID from the JWT subject
      # The Convex JWT Subject used for the user_id contains `[32 character user ID]|[user session ID]`
      user_lists: SELECT uuid from lists where archived != true AND owner_id = substring(auth.user_id(), 1, 32)
    # AUTO-SUBSCRIBE: always synced for the logged-in user
    auto_subscribe: true
    queries:
      - |
        SELECT uuid as id, *
        FROM lists
        WHERE uuid in user_lists
      - |
        SELECT uuid as id, list_uuid as list_id, *
        FROM todos
        WHERE list_uuid IN user_lists
  archived_user_data:
    # We don't sync archvied data, but we allow users to condiftionally subsribe to it for a period of time.
    # IMPROVE ME:: This should be filtered further in furtue.
    with:
      # Extract the Convex user ID from the JWT subject
      # The Convex JWT Subject used for the user_id contains `[32 character user ID]|[user session ID]`
      archived_user_lists: SELECT uuid from lists where archived = true AND owner_id = substring(auth.user_id(), 1, 32)
    queries:
      - |
        SELECT uuid as id, *
        FROM lists
        WHERE uuid in archived_user_lists
      - |
        SELECT uuid as id, list_uuid as list_id, *
        FROM todos
        WHERE list_uuid IN archived_user_lists
