/**
 * Script that replaces 'demos/.../package.json' with 'demos/.../package.json.bak',
 * which is generated by 'scripts/demos-use-workspace.ts'.
 */

import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

const demosDir = path.resolve('demos');

// Function to split user-provided demos into found and not found demos
const filterDemos = (allDemos: string[], providedDemos: string[]): [string[], string[]] => {
  const found: string[] = [];
  const notFound: string[] = [];

  providedDemos.forEach((demo) => {
    if (allDemos.includes(demo)) {
      found.push(demo);
    } else {
      notFound.push(demo);
    }
  });

  return [found, notFound];
};

// Function to replace '^x.xx.xx' with 'workspace:*' for workspace packages
const linkDemo = async (demoName: string) => {
  const demoSrc = path.join(demosDir, demoName);
  console.log(`Unlinking ${demoName}`);

  // Update package.json
  const packageJsonPath = path.join(demoSrc, 'package.json');
  const packageJsonBakPath = path.join(demoSrc, 'package.json.bak');

  if (!fs.existsSync(packageJsonBakPath)) {
    console.log("⚠️ Warning: No 'package.json.bak'.");
    return;
  }

  // Replace package.json with package.json.bak
  fs.copyFileSync(packageJsonBakPath, packageJsonPath);
  fs.unlinkSync(packageJsonBakPath);
};

// Main function to read demos directory and process each demo
const main = () => {
  const args: string[] = [];
  const opts = {
    noInstall: false
  };

  for (const arg of process.argv.slice(2)) {
    if (arg === '--no-install') {
      opts.noInstall = true;
    } else {
      args.push(arg);
    }
  }

  const allDemos = fs.readdirSync(demosDir);
  let demoNames: string[];

  if (args.length > 0) {
    const [foundDemos, notFoundDemos] = filterDemos(allDemos, process.argv.slice(2));

    if (notFoundDemos.length > 0) {
      console.log('⚠️ Warning: Failed to locate some demos:');
      for (const demo of notFoundDemos) {
        console.log(`   - ${demo}`);
      }
    }

    demoNames = foundDemos;
  } else {
    demoNames = allDemos;
  }

  console.log('Unlinking demos...');
  for (const demoName of demoNames) {
    linkDemo(demoName);
  }
  console.log('Done.');

  if (opts.noInstall) {
    process.exit(0);
  }

  console.log('\nInstalling packages...');
  for (const demoName of demoNames) {
    const demoSrc = path.join(demosDir, demoName);
    try {
      execSync('pnpm --ignore-workspace install', { cwd: demoSrc, stdio: 'inherit' });
    } catch (e) {
      console.error(`Error installing packages: ${e}`);
      process.exit(1);
    }
    console.log('Done.');
  }
};

main();
