/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSyncDiagnosticsRouteImport } from './routes/_authenticated/sync-diagnostics'
import { Route as AuthenticatedSqlConsoleRouteImport } from './routes/_authenticated/sql-console'
import { Route as AuthenticatedSchemaRouteImport } from './routes/_authenticated/schema'
import { Route as AuthenticatedClientParametersRouteImport } from './routes/_authenticated/client-parameters'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSyncDiagnosticsRoute =
  AuthenticatedSyncDiagnosticsRouteImport.update({
    id: '/sync-diagnostics',
    path: '/sync-diagnostics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSqlConsoleRoute = AuthenticatedSqlConsoleRouteImport.update({
  id: '/sql-console',
  path: '/sql-console',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchemaRoute = AuthenticatedSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientParametersRoute =
  AuthenticatedClientParametersRouteImport.update({
    id: '/client-parameters',
    path: '/client-parameters',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/client-parameters': typeof AuthenticatedClientParametersRoute
  '/schema': typeof AuthenticatedSchemaRoute
  '/sql-console': typeof AuthenticatedSqlConsoleRoute
  '/sync-diagnostics': typeof AuthenticatedSyncDiagnosticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/client-parameters': typeof AuthenticatedClientParametersRoute
  '/schema': typeof AuthenticatedSchemaRoute
  '/sql-console': typeof AuthenticatedSqlConsoleRoute
  '/sync-diagnostics': typeof AuthenticatedSyncDiagnosticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/client-parameters': typeof AuthenticatedClientParametersRoute
  '/_authenticated/schema': typeof AuthenticatedSchemaRoute
  '/_authenticated/sql-console': typeof AuthenticatedSqlConsoleRoute
  '/_authenticated/sync-diagnostics': typeof AuthenticatedSyncDiagnosticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/client-parameters'
    | '/schema'
    | '/sql-console'
    | '/sync-diagnostics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/client-parameters'
    | '/schema'
    | '/sql-console'
    | '/sync-diagnostics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/client-parameters'
    | '/_authenticated/schema'
    | '/_authenticated/sql-console'
    | '/_authenticated/sync-diagnostics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sync-diagnostics': {
      id: '/_authenticated/sync-diagnostics'
      path: '/sync-diagnostics'
      fullPath: '/sync-diagnostics'
      preLoaderRoute: typeof AuthenticatedSyncDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sql-console': {
      id: '/_authenticated/sql-console'
      path: '/sql-console'
      fullPath: '/sql-console'
      preLoaderRoute: typeof AuthenticatedSqlConsoleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schema': {
      id: '/_authenticated/schema'
      path: '/schema'
      fullPath: '/schema'
      preLoaderRoute: typeof AuthenticatedSchemaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/client-parameters': {
      id: '/_authenticated/client-parameters'
      path: '/client-parameters'
      fullPath: '/client-parameters'
      preLoaderRoute: typeof AuthenticatedClientParametersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedClientParametersRoute: typeof AuthenticatedClientParametersRoute
  AuthenticatedSchemaRoute: typeof AuthenticatedSchemaRoute
  AuthenticatedSqlConsoleRoute: typeof AuthenticatedSqlConsoleRoute
  AuthenticatedSyncDiagnosticsRoute: typeof AuthenticatedSyncDiagnosticsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientParametersRoute: AuthenticatedClientParametersRoute,
  AuthenticatedSchemaRoute: AuthenticatedSchemaRoute,
  AuthenticatedSqlConsoleRoute: AuthenticatedSqlConsoleRoute,
  AuthenticatedSyncDiagnosticsRoute: AuthenticatedSyncDiagnosticsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
