import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { packageMap } from './utils/packageMap';

const items = Object.values(packageMap).map((config) => ({
  type: 'category',
  label: config.name,
  items: [
    {
      type: 'autogenerated',
      dirName: config.dirName
    }
  ]
})) as unknown as SidebarsConfig;

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Libraries',
      collapsible: false,
      items
    }
  ]
};

export default sidebars;
