services:
  # MongoDB Service used internally
  mongo:
    image: mongo:8.0
    command: --replSet rs0 --bind_ip_all --quiet
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_storage:/data/db
    healthcheck:
      test:
        - CMD
        - mongosh
        - --quiet
        - --host
        - mongo:27017
        - --eval
        - 'db.adminCommand("ping").ok'
      interval: 1s
      timeout: 5s
      retries: 30

  # Initializes the MongoDB replica set. This service will not usually be actively running
  mongo-rs-init:
    image: mongo:8.0
    depends_on:
      mongo:
        condition: service_healthy
    restart: on-failure
    entrypoint:
      - bash
      - -c
      - 'mongosh --host mongo:27017 --eval ''try{rs.status().ok && quit(0)} catch {} rs.initiate({_id: "rs0", version: 1, members: [{ _id: 0, host : "mongo:27017" }]})'''

volumes:
  mongo_storage:
