name: Build docs

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ALGOLIA_APP_ID: 123
      ALGOLIA_API_KEY: 123
      GH_URL: http://example.test
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Enable Corepack
        run: corepack enable
      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
      - name: Build Packages
        run: pnpm build:packages
      - name: Build Docs
        run: pnpm docs:build
