# Ensures packages test correctly
name: Test Packages

on:
  push:

jobs:
  test:
    name: Test Packages
    runs-on: ubuntu-xl
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Configure Playwright
        run: |
          pnpm exec playwright install-deps
          pnpm exec playwright install
      
      - name: Install system libraries for Tauri integration tests
        # https://v2.tauri.app/start/prerequisites/#linux
        run: sudo apt install libwebkit2gtk-4.1-dev build-essential curl  wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Build
        run: pnpm build:packages

      - name: Test
        run: pnpm test
