# Ensures certain packages work on simulators
name: Test Emulators

on:
  push:

jobs:
  test:
    name: Test Android
    runs-on: ubuntu-xl
    env:
      AVD_NAME: ubuntu-avd-x86_64-31
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle Cache
        uses: gradle/gradle-build-action@v2

      - name: AVD Cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-31

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:packages

      - name: Install Detox dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils
          npm install -g detox-cli
          detox clean-framework-cache && detox build-framework-cache

      - name: Initialize Android Folder
        run: mkdir -p ~/.android/avd

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2.28.0
        with:
          api-level: 31
          force-avd-creation: false
          target: google_apis
          arch: x86_64
          disable-animations: false
          avd-name: $AVD_NAME
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: echo "Generated AVD snapshot for caching."

      - name: Run connected Android tests
        uses: ReactiveCircus/android-emulator-runner@v2.28.0
        with:
          api-level: 31
          target: google_apis
          arch: x86_64
          avd-name: $AVD_NAME
          script: pnpm android
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true

      - name: Android Emulator Build
        working-directory: ./tools/powersynctests
        run: pnpx detox build --configuration android.emu.release

      - name: Android Emultator Test
        working-directory: ./tools/powersynctests
        run: pnpx detox test --configuration android.emu.release --headless
